---
run_name: Meta-Llama-3.1-70B-Instruct_float16_re_multiclass
log_dir: /home/ehsu/David_projects/LLM-IE_benchmark/benchmarks/ADE medication 2018/log/
id_file: /home/ehsu/David_projects/LLM-IE_benchmark/benchmarks/ADE medication 2018/doc_id/test_id
base_url: http://localhost:8000/v1
prompt_template: /home/ehsu/David_projects/LLM-IE_benchmark/benchmarks/ADE medication 2018/prompt_templates/RE_multiclass.txt
system_prompt: "You are a highly skilled clinical AI assistant, proficient in reviewing clinical notes and performing accurate information extraction"
llmie_dir: /home/ehsu/David_projects/LLM-IE_benchmark/benchmarks/ADE medication 2018/llmie/gold/
out_dir: /home/ehsu/David_projects/LLM-IE_benchmark/benchmarks/ADE medication 2018/llmie/
